baseURL = "/"
defaultContentLanguage = "zh"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
author = "MDFriday (mdfriday.com)"
description = "Site description for SEO"
googleAnalytics = "GA-000000000-0"

[module]
    [[module.imports]]
        path = "github.com/mdfriday/theme-initio"

[params]
    banner = "banner_mountain.jpeg"


[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true
